# THIS FILE WAS GENERATED BY RENPAC! DO NOT MODIFY MANUALLY AS CHANGES MAY BE OVERWRITTEN
# To make changes, modify bardolf.cfg and run the generator again.

init python:
    def load_game():
        coin = Item()
        coin.desc = "This special coin depoicting a three-legged horse is from an ancient group called the Hunters. Other than that, you do not know much about it."
        gruel = Item()
        shackles = Item()
        shackles.desc = "Rusty shackles chain you to the ground. They look weak, though."
        shackles.fixed = True
        food bag = Item()
        food_bag.desc = "This bag smells of delicious food!"
        cell = Room()
        cell.desc = "A foul stench assaults you from all around. In one wall a slit serves as a window, letting in just enough light to see."
        cell.first_desc = "You wake with a vicious pounding in your head and find yourself on the upper floor of a tower. Looks like a cell."
        cell.printed_name = "Dungeon Cell"
        cell.hotspot_add(cell_stairs)
        cell.hotspot_add(gruel)
        cell.hotspot_add(shackles)
        guardhouse = Room()
        guardhouse.desc = "This guardhouse has seen better days. Was it attacked recently? Stairs lead back up to the cell."
        guardhouse.printed_name = "Guardhouse"
        guardhouse.hotspot_add(guardhouse_stairs)
