import os

from Config import *

class Script:
    _text = ""

    @staticmethod
    def add_header(header: str) -> None:
        Script._text += f"\n###\n# {header}\n###\n"

    @staticmethod
    def add_line(line: str) -> None:
        Script._text += f"{line}\n"

    @staticmethod
    def clear() -> None:
        Script._text = ""
    
    @staticmethod
    def print() -> None:
        print(Script._text)

    @staticmethod
    def write_file(filename: str) -> None:
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        with open(filename, "w") as file:
            file.write("# THIS FILE WAS GENERATED BY RENPAC\n"
                "# DO **NOT** MODIFY MANUALLY, AS CHANGES MAY BE OVERWRITTEN!\n"
                f"# To make changes, modify {Config.filename} and run the generator again.\n\n"
                f"init python:\n"
                f"    def load_game():\n")
            for line in Script._text.splitlines():
                file.write(f"        {line}\n")